### ISSUE TITLE
打不开啊

### ISSUE THREAD

**Issue by eee555** [putianyi889/MS-Texture#1]
是不是没保存？打开是这样的：
<?xml version="1.0" standalone="yes"?>
<svg width="160" height="160" xmlns="http://www.w3.org/2000/svg">
	<image href="celldown.svg" />
	<image href="num7.svg" />
</svg>

**Comment by eee555** [comment]
<?xml version="1.0" standalone="yes"?>
<svg width="160" height="160" xmlns="http://www.w3.org/2000/svg">
	<image href="celldown.svg" />
	<image href="num7.svg" />
</svg>

**Comment by eee555** [comment]
`<?xml version="1.0" standalone="yes"?>
<svg width="160" height="160" xmlns="http://www.w3.org/2000/svg">
	<image href="celldown.svg" />
	<image href="num7.svg" />
</svg>`

**Comment by eee555** [comment]
```
<?xml version="1.0" standalone="yes"?>
<svg width="160" height="160" xmlns="http://www.w3.org/2000/svg">
	<image href="celldown.svg" />
	<image href="num7.svg" />
</svg>
```

**Comment by putianyi889** [comment]
重构了代码，取消了所有的载入外部svg操作
